### ISSUE TITLE
How do you generate migrations with methods?

### ISSUE THREAD

**Issue by danielbrutti** [jgabriel1/expo-sqlite-typeorm-article#2]
Hi,

I have a silly question... in the typeorm migration file you are using functions like `queryRunner.createTable` instead of SQL. When I do the `migration:create` or migration:generate` commands the migrations are created using `queryRunner.query` with SQL code.

Is this some kind of typeorm configuration? or did you code the migrations?

Thanks!

**Comment by jgabriel1** [comment]
Hello, I'm sorry I never got to respond this. But in case you're still interested, I'll respond anyways.

Yes, I coded the migrations separately. It is totally not necessary though, the end result of having TypeORM generate them is the same.

I don't know for sure if you can configure TypeORM to generate migrations using their own API instead of raw SQL.

P.S.: Again, sorry for never seeing this and responding 2 months late, I just stumbled upon it now. I wasn't really checking for anything here, I only occasionally check the post itself.

**Comment by danielbrutti** [comment]
No problem, at the end we are using plain SQL.. but we might migrate them in the future before go prod. thanks!
